//
// Created by 陈瀚泽 on 2019/3/10.
//

#ifndef DUNGEON_COMS327_F19_WINDOW_STATUSBAR_H
#define DUNGEON_COMS327_F19_WINDOW_STATUSBAR_H
#include <ncurses.h>

WINDOW * initStatusBar();
#endif //DUNGEON_COMS327_F19_WINDOW_STATUSBAR_H
