#ifndef DUNGEON_V1_01_DISPLAY_COMMON_H
#define DUNGEON_V1_01_DISPLAY_COMMON_H

#define PAIR_STATUS_BAR 1
#define PAIR_DUNGEON_WINDOW 2
#define PAIR_CHARACTER_STATUS 3
#define PAIR_PANEL 4
#endif //DUNGEON_V1_01_DISPLAY_UTILS_H