#ifndef DUNGEON_V1_01_DISPLAY_COMMON_H
#define DUNGEON_V1_01_DISPLAY_COMMON_H

#define PAIR_PANEL 4
#define PAIR_STATUS_BAR 1
#define PAIR_DUNGEON_WINDOW 2
#define PAIR_CHARACTER_STATUS 3

#define PAIR_RED 5
#define PAIR_BLUE 6
#define PAIR_CYAN 7
#define PAIR_GREEN 8
#define PAIR_WHITE 9
#define PAIR_BLACK 10
#define PAIR_YELLOW 11
#define PAIR_MAGENTA 12

#endif